/**
 * Site Configuration — generated by SiteAssembler
 * Design: premium-magazine-a-1785410790899 (brief-composed)
 * DO NOT EDIT MANUALLY
 */

export interface NavCategory {
  name: string;
  slug: string;
}

export interface ComponentVariantConfig {
  variant: string;
  options?: Record<string, unknown>;
}

export interface RecipeSlot {
  id: string;
  kind: string;
  block: string;
  span?: string;
  limit?: number;
  categorySlug?: string;
  options?: Record<string, unknown>;
}

export interface HomepageRecipe {
  schemaVersion: 'recipe-v1';
  id: string;
  page: 'homepage';
  homepageLayout?: string;
  rhythmId?: string;
  slots: RecipeSlot[];
  grid?: 'single' | 'main-sidebar' | 'mosaic-12' | 'scoreboard-split';
}

export type HeaderFamily =
  | 'broadcast-scoreboard'
  | 'editorial-centered'
  | 'newsroom-command'
  | 'regional-utility'
  | 'visual-trending'
  | 'business-markets';

export type FooterFamily =
  | 'sports-clubhouse'
  | 'editorial-statement'
  | 'dense-directory'
  | 'regional-service'
  | 'compact-newsroom';

export interface ChromeConfig {
  schemaVersion: 'chrome-v1';
  header: {
    family: HeaderFamily;
    brandPosition: 'left' | 'center' | 'split';
    navPosition: 'inside-main' | 'below-main' | 'none';
    breakingPosition: 'top' | 'below-nav' | 'inside-header' | 'none';
    searchMode: 'icon' | 'expanded' | 'hidden';
    stickyMode: 'full' | 'compact' | 'nav-only' | 'none';
    logoScale: 'compact' | 'standard' | 'masthead';
    edgeStyle: 'flat' | 'bordered' | 'layered';
    motionProfile: 'minimal' | 'editorial' | 'energetic';
    signatureModule:
      | 'live-score-indicator'
      | 'breaking-command-strip'
      | 'region-selector'
      | 'edition-date'
      | 'trending-carousel'
      | 'market-pulse'
      | 'none';
    surface: 'dark' | 'light';
  };
  footer: {
    family: FooterFamily;
    brandScale: 'small' | 'medium' | 'large';
    backgroundTreatment: 'solid' | 'split' | 'tonal';
    columnRhythm: 'balanced' | 'asymmetric' | 'stacked';
    showNewsletter: boolean;
    showSocialWall: boolean;
    showPopularTopics: boolean;
    showAppPromotion: boolean;
  };
}

export interface SiteConfig {
  siteName: string;
  tagline: string;
  description: string;
  locale: {
    language: string;
    dialect: string;
    timezone: string;
  };
  cms: {
    baseUrl: string;
    websiteKey: string;
    collections: string[];
  };
  seo: {
    canonicalHost?: string;
    defaultOgImage: string;
  };
  layouts: {
    homepage: string;
    category: string;
    article: string;
    search: string;
  };
  density: 'high' | 'balanced' | 'low';
  motion: 'none' | 'restrained' | 'moderate' | 'energetic';
  components: {
    header: ComponentVariantConfig;
    breakingNews: ComponentVariantConfig;
    featuredCard: ComponentVariantConfig;
    standardCard: ComponentVariantConfig;
    footer: ComponentVariantConfig;
  };
  navCategories: NavCategory[];
  homepageRecipe?: HomepageRecipe;
  componentRegistry?: {
    version: 1;
    updatedAt: string;
    blocks: Array<{
      blockId: string;
      kind: string;
      baseBlock: string;
      displayName: string;
      options?: Record<string, unknown>;
      wrapperClass?: string;
    }>;
  };
  capabilities?: {
    enabled: string[];
  };
  chrome?: ChromeConfig;
}

export const siteConfig: SiteConfig = {
  siteName: "Placar Nacional",
  tagline: "",
  description: "analytical · in-depth · measured",
  locale: {"language":"pt","dialect":"pt-BR","timezone":"America/Sao_Paulo"},
  cms: {
    baseUrl: process.env.NEXT_PUBLIC_CMS_URL || 'http://localhost:8000/api',
    websiteKey: "placar-nacional-fyzq",
    collections: ["feed_brazil","aiarticles"],
  },
  seo: {
    defaultOgImage: "/og-image.jpg",
  },
  layouts: {
    "homepage": "brief-composed",
    "category": "section-led-grid",
    "article": "longform-focused",
    "search": "editorial-results"
  },
  density: "balanced",
  motion: "restrained",
  components: {
    "header": {
      "variant": "compact-utility",
      "options": {}
    },
    "breakingNews": {
      "variant": "static-banner"
    },
    "featuredCard": {
      "variant": "image-first-large",
      "options": {
        "aspectRatio": "16:9"
      }
    },
    "standardCard": {
      "variant": "vertical-editorial"
    },
    "footer": {
      "variant": "expanded-editorial",
      "options": {}
    }
  },
  navCategories: [
    {
      "name": "últimas notícias",
      "slug": "ultimas-noticias"
    },
    {
      "name": "política",
      "slug": "politica"
    },
    {
      "name": "economia",
      "slug": "economia"
    },
    {
      "name": "negócios",
      "slug": "negocios"
    },
    {
      "name": "tecnologia",
      "slug": "tecnologia"
    },
    {
      "name": "esportes",
      "slug": "esportes"
    },
    {
      "name": "entretenimento",
      "slug": "entretenimento"
    },
    {
      "name": "cultura",
      "slug": "cultura"
    },
    {
      "name": "saúde",
      "slug": "saude"
    },
    {
      "name": "ciência",
      "slug": "ciencia"
    },
    {
      "name": "meio ambiente",
      "slug": "meio-ambiente"
    },
    {
      "name": "acontecimentos nacionais",
      "slug": "acontecimentos-nacionais"
    },
    {
      "name": "acontecimentos internacionais",
      "slug": "acontecimentos-internacionais"
    }
  ],
  homepageRecipe: {
    "schemaVersion": "recipe-v1",
    "id": "brief-premium-magazine-a-1785410790899-a",
    "page": "homepage",
    "homepageLayout": "brief-composed",
    "rhythmId": "rhythm-brief",
    "grid": "main-sidebar",
    "slots": [
      {
        "id": "lead",
        "kind": "hero",
        "block": "HeroLead",
        "span": "full",
        "limit": 1,
        "options": {
          "source": "brief"
        }
      },
      {
        "id": "latest-rail",
        "kind": "ranked-rail",
        "block": "RankedRail",
        "span": "full",
        "limit": 5,
        "options": {}
      },
      {
        "id": "ultimas",
        "kind": "stream",
        "block": "HorizontalStream",
        "limit": 8,
        "options": {}
      },
      {
        "id": "nacional",
        "kind": "section-pair",
        "block": "DualSection",
        "limit": 2,
        "options": {}
      },
      {
        "id": "mais-lidas",
        "kind": "most-read",
        "block": "MostReadPanel",
        "limit": 5,
        "options": {}
      },
      {
        "id": "newsletter",
        "kind": "newsletter",
        "block": "NewsletterCard",
        "options": {}
      }
    ]
  },
  componentRegistry: {
    "version": 1,
    "updatedAt": "2026-07-30T00:00:00.000Z",
    "blocks": []
  },
  capabilities: {
    "enabled": [
      "breaking-ticker",
      "search",
      "category-nav"
    ]
  },
  chrome: {
    "schemaVersion": "chrome-v1",
    "header": {
      "family": "business-markets",
      "brandPosition": "center",
      "navPosition": "inside-main",
      "breakingPosition": "inside-header",
      "searchMode": "expanded",
      "stickyMode": "full",
      "logoScale": "compact",
      "edgeStyle": "bordered",
      "motionProfile": "minimal",
      "signatureModule": "market-pulse",
      "surface": "light"
    },
    "footer": {
      "family": "sports-clubhouse",
      "brandScale": "large",
      "backgroundTreatment": "solid",
      "columnRhythm": "asymmetric",
      "showNewsletter": false,
      "showSocialWall": true,
      "showPopularTopics": true,
      "showAppPromotion": true
    }
  },
};
