/**
 * Site-specific demo content — generated by SiteAssembler
 * Site: Placar Nacional
 * DO NOT EDIT MANUALLY
 */

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  categorySlug: string;
  author: string;
  publishedAt: string;
  imageUrl?: string;
  isVideo?: boolean;
  readCount?: number;
  featured?: boolean;
  keyPoints?: string[];
}

export interface BreakingHeadline {
  id: string;
  text: string;
  slug?: string;
  urgent?: boolean;
}

export interface AlertItem {
  id: string;
  level: string;
  title: string;
  href?: string;
  publishedAt: string;
}

export interface LiveUpdate {
  id: string;
  at: string;
  source: string;
  text: string;
}

export interface LiveStory {
  id: string;
  slug: string;
  title: string;
  summary: string;
  updatedAt: string;
  updates: LiveUpdate[];
}

export const categories: Category[] = [
  {
    "id": "cat-ultimas-noticias",
    "name": "últimas notícias",
    "slug": "ultimas-noticias",
    "description": "Cobertura de últimas notícias em Placar Nacional"
  },
  {
    "id": "cat-politica",
    "name": "política",
    "slug": "politica",
    "description": "Cobertura de política em Placar Nacional"
  },
  {
    "id": "cat-economia",
    "name": "economia",
    "slug": "economia",
    "description": "Cobertura de economia em Placar Nacional"
  },
  {
    "id": "cat-negocios",
    "name": "negócios",
    "slug": "negocios",
    "description": "Cobertura de negócios em Placar Nacional"
  },
  {
    "id": "cat-tecnologia",
    "name": "tecnologia",
    "slug": "tecnologia",
    "description": "Cobertura de tecnologia em Placar Nacional"
  },
  {
    "id": "cat-esportes",
    "name": "esportes",
    "slug": "esportes",
    "description": "Cobertura de esportes em Placar Nacional"
  },
  {
    "id": "cat-entretenimento",
    "name": "entretenimento",
    "slug": "entretenimento",
    "description": "Cobertura de entretenimento em Placar Nacional"
  },
  {
    "id": "cat-cultura",
    "name": "cultura",
    "slug": "cultura",
    "description": "Cobertura de cultura em Placar Nacional"
  }
];

export const breakingHeadlines: BreakingHeadline[] = [
  {
    "id": "brk-1",
    "text": "AO VIVO — últimas notícias: atualização urgente para leitores de Placar Nacional",
    "slug": "por-que-ultimas-noticias-domina-a-conversa-e-o-que-vem-a-seguir-3na",
    "urgent": true
  },
  {
    "id": "brk-2",
    "text": "AO VIVO — política: atualização urgente para leitores de Placar Nacional",
    "slug": "placar-nacional-explica-o-ponto-chave-de-ultimas-noticias-nesta-semana-3nb",
    "urgent": false
  },
  {
    "id": "brk-3",
    "text": "AO VIVO — economia: atualização urgente para leitores de Placar Nacional",
    "slug": "ultimas-noticias-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-p-3nc",
    "urgent": false
  }
];

export const articles: Article[] = [
  {
    "id": "art-1",
    "slug": "por-que-ultimas-noticias-domina-a-conversa-e-o-que-vem-a-seguir-3na",
    "title": "Por que últimas notícias domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>últimas notícias</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "últimas notícias",
    "categorySlug": "ultimas-noticias",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-08-02T10:24:56.230Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 29926,
    "featured": true,
    "isVideo": true,
    "keyPoints": [
      "O que aconteceu em últimas notícias e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 6)."
    ]
  },
  {
    "id": "art-2",
    "slug": "placar-nacional-explica-o-ponto-chave-de-ultimas-noticias-nesta-semana-3nb",
    "title": "Placar Nacional explica: o ponto-chave de últimas notícias nesta semana",
    "excerpt": "Leitura direta para quem acompanha últimas notícias no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>últimas notícias</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "últimas notícias",
    "categorySlug": "ultimas-noticias",
    "author": "Hugo Almeida",
    "publishedAt": "2026-08-02T03:24:56.230Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 30923,
    "featured": true,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em últimas notícias e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 7)."
    ]
  },
  {
    "id": "art-3",
    "slug": "ultimas-noticias-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-p-3nc",
    "title": "últimas notícias: o que muda agora e o impacto direto para o público de Placar Nacional",
    "excerpt": "Cobertura rápida e objetiva sobre últimas notícias, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>últimas notícias</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "últimas notícias",
    "categorySlug": "ultimas-noticias",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-08-01T20:24:56.230Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 31920,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em últimas notícias e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 8)."
    ]
  },
  {
    "id": "art-4",
    "slug": "bastidores-de-politica-analise-com-numeros-e-contexto-3nd",
    "title": "Bastidores de política — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>política</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "política",
    "categorySlug": "politica",
    "author": "Bruno Costa",
    "publishedAt": "2026-08-01T13:24:56.230Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 32917,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em política e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 9)."
    ]
  },
  {
    "id": "art-5",
    "slug": "ultima-hora-em-politica-decisoes-que-mexem-com-a-rodada-3ne",
    "title": "Última hora em política: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha política no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>política</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "política",
    "categorySlug": "politica",
    "author": "Camila Souza",
    "publishedAt": "2026-08-04T06:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 33914,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em política e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 10)."
    ]
  },
  {
    "id": "art-6",
    "slug": "politica-em-foco-tres-leituras-que-importam-hoje-3nf",
    "title": "política em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre política, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>política</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "política",
    "categorySlug": "politica",
    "author": "Diego Martins",
    "publishedAt": "2026-08-03T23:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 34911,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em política e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 11)."
    ]
  },
  {
    "id": "art-7",
    "slug": "por-que-economia-domina-a-conversa-e-o-que-vem-a-seguir-3ng",
    "title": "Por que economia domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>economia</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "economia",
    "categorySlug": "economia",
    "author": "Elena Prado",
    "publishedAt": "2026-08-03T16:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 35908,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em economia e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 12)."
    ]
  },
  {
    "id": "art-8",
    "slug": "placar-nacional-explica-o-ponto-chave-de-economia-nesta-semana-3nh",
    "title": "Placar Nacional explica: o ponto-chave de economia nesta semana",
    "excerpt": "Leitura direta para quem acompanha economia no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>economia</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "economia",
    "categorySlug": "economia",
    "author": "Felipe Nunes",
    "publishedAt": "2026-08-03T09:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 36905,
    "featured": false,
    "isVideo": true,
    "keyPoints": [
      "O que aconteceu em economia e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 13)."
    ]
  },
  {
    "id": "art-9",
    "slug": "economia-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-placar-na-3ni",
    "title": "economia: o que muda agora e o impacto direto para o público de Placar Nacional",
    "excerpt": "Cobertura rápida e objetiva sobre economia, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>economia</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "economia",
    "categorySlug": "economia",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-08-03T02:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 37902,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em economia e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 14)."
    ]
  },
  {
    "id": "art-10",
    "slug": "bastidores-de-negocios-analise-com-numeros-e-contexto-3nj",
    "title": "Bastidores de negócios — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>negócios</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "negócios",
    "categorySlug": "negocios",
    "author": "Hugo Almeida",
    "publishedAt": "2026-08-02T19:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 38899,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-11",
    "slug": "ultima-hora-em-negocios-decisoes-que-mexem-com-a-rodada-3nk",
    "title": "Última hora em negócios: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha negócios no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>negócios</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "negócios",
    "categorySlug": "negocios",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-08-02T12:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 39896,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em negócios e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 16)."
    ]
  },
  {
    "id": "art-12",
    "slug": "negocios-em-foco-tres-leituras-que-importam-hoje-3nl",
    "title": "negócios em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre negócios, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>negócios</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "negócios",
    "categorySlug": "negocios",
    "author": "Bruno Costa",
    "publishedAt": "2026-08-02T05:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 40893,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-13",
    "slug": "por-que-tecnologia-domina-a-conversa-e-o-que-vem-a-seguir-3nm",
    "title": "Por que tecnologia domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>tecnologia</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "tecnologia",
    "categorySlug": "tecnologia",
    "author": "Camila Souza",
    "publishedAt": "2026-08-01T22:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 41890,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em tecnologia e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 18)."
    ]
  },
  {
    "id": "art-14",
    "slug": "placar-nacional-explica-o-ponto-chave-de-tecnologia-nesta-semana-3nn",
    "title": "Placar Nacional explica: o ponto-chave de tecnologia nesta semana",
    "excerpt": "Leitura direta para quem acompanha tecnologia no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>tecnologia</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "tecnologia",
    "categorySlug": "tecnologia",
    "author": "Diego Martins",
    "publishedAt": "2026-08-01T15:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 42887,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-15",
    "slug": "tecnologia-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-placar--3no",
    "title": "tecnologia: o que muda agora e o impacto direto para o público de Placar Nacional",
    "excerpt": "Cobertura rápida e objetiva sobre tecnologia, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>tecnologia</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "tecnologia",
    "categorySlug": "tecnologia",
    "author": "Elena Prado",
    "publishedAt": "2026-08-04T08:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 43884,
    "featured": false,
    "isVideo": true,
    "keyPoints": [
      "O que aconteceu em tecnologia e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 20)."
    ]
  },
  {
    "id": "art-16",
    "slug": "bastidores-de-esportes-analise-com-numeros-e-contexto-3np",
    "title": "Bastidores de esportes — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>esportes</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "esportes",
    "categorySlug": "esportes",
    "author": "Felipe Nunes",
    "publishedAt": "2026-08-04T01:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 44881,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-17",
    "slug": "ultima-hora-em-esportes-decisoes-que-mexem-com-a-rodada-3nq",
    "title": "Última hora em esportes: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha esportes no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>esportes</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "esportes",
    "categorySlug": "esportes",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-08-03T18:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 45878,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em esportes e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 22)."
    ]
  },
  {
    "id": "art-18",
    "slug": "esportes-em-foco-tres-leituras-que-importam-hoje-3nr",
    "title": "esportes em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre esportes, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>esportes</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "esportes",
    "categorySlug": "esportes",
    "author": "Hugo Almeida",
    "publishedAt": "2026-08-03T11:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 46875,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-19",
    "slug": "por-que-entretenimento-domina-a-conversa-e-o-que-vem-a-seguir-3ns",
    "title": "Por que entretenimento domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>entretenimento</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "entretenimento",
    "categorySlug": "entretenimento",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-08-03T04:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 47872,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em entretenimento e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 24)."
    ]
  },
  {
    "id": "art-20",
    "slug": "placar-nacional-explica-o-ponto-chave-de-entretenimento-nesta-semana-3nt",
    "title": "Placar Nacional explica: o ponto-chave de entretenimento nesta semana",
    "excerpt": "Leitura direta para quem acompanha entretenimento no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>entretenimento</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "entretenimento",
    "categorySlug": "entretenimento",
    "author": "Bruno Costa",
    "publishedAt": "2026-08-02T21:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 48869,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-21",
    "slug": "entretenimento-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-pla-3nu",
    "title": "entretenimento: o que muda agora e o impacto direto para o público de Placar Nacional",
    "excerpt": "Cobertura rápida e objetiva sobre entretenimento, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>entretenimento</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "entretenimento",
    "categorySlug": "entretenimento",
    "author": "Camila Souza",
    "publishedAt": "2026-08-02T14:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 1866,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em entretenimento e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 26)."
    ]
  },
  {
    "id": "art-22",
    "slug": "bastidores-de-cultura-analise-com-numeros-e-contexto-3nv",
    "title": "Bastidores de cultura — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>cultura</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "cultura",
    "categorySlug": "cultura",
    "author": "Diego Martins",
    "publishedAt": "2026-08-02T07:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 2863,
    "featured": false,
    "isVideo": true
  },
  {
    "id": "art-23",
    "slug": "ultima-hora-em-cultura-decisoes-que-mexem-com-a-rodada-3nw",
    "title": "Última hora em cultura: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha cultura no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>cultura</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "cultura",
    "categorySlug": "cultura",
    "author": "Elena Prado",
    "publishedAt": "2026-08-02T00:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 3860,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em cultura e por que importa para leitores de Placar Nacional.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 28)."
    ]
  },
  {
    "id": "art-24",
    "slug": "cultura-em-foco-tres-leituras-que-importam-hoje-3nx",
    "title": "cultura em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre cultura, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Placar Nacional</strong> na seção <em>cultura</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "cultura",
    "categorySlug": "cultura",
    "author": "Felipe Nunes",
    "publishedAt": "2026-08-01T17:24:56.231Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 4857,
    "featured": false,
    "isVideo": false
  }
];

export const alerts: AlertItem[] = [
  {
    "id": "alert-1",
    "level": "Urgente",
    "title": "Atualização crítica em últimas notícias — acompanhe minuto a minuto",
    "href": "/artigo/por-que-ultimas-noticias-domina-a-conversa-e-o-que-vem-a-seguir-3na",
    "publishedAt": "2026-08-02T10:24:56.231Z"
  },
  {
    "id": "alert-2",
    "level": "Importante",
    "title": "Placar Nacional: comunicado oficial sobre cobertura em tempo real",
    "href": "/alertas",
    "publishedAt": "2026-08-02T03:24:56.231Z"
  },
  {
    "id": "alert-3",
    "level": "Aviso",
    "title": "Manutenção programada da área de alertas (demo)",
    "publishedAt": "2026-08-01T20:24:56.231Z"
  },
  {
    "id": "alert-4",
    "level": "Urgente",
    "title": "Desenvolvimento em política com impacto nacional",
    "href": "/artigo/placar-nacional-explica-o-ponto-chave-de-ultimas-noticias-nesta-semana-3nb",
    "publishedAt": "2026-08-01T13:24:56.232Z"
  },
  {
    "id": "alert-5",
    "level": "Importante",
    "title": "Fontes oficiais confirmam novo capítulo da história em acompanhamento",
    "publishedAt": "2026-08-04T06:24:56.232Z"
  },
  {
    "id": "alert-6",
    "level": "Aviso",
    "title": "Lembrete editorial: confira a política de atualização ao vivo",
    "href": "/sobre",
    "publishedAt": "2026-08-03T23:24:56.232Z"
  }
];

export const liveStories: LiveStory[] = [
  {
    "id": "live-1",
    "slug": "demo-nacional",
    "title": "AO VIVO — Cobertura nacional de Placar Nacional",
    "summary": "Linha do tempo demonstrativa com fontes rotuladas e âncoras estáveis.",
    "updatedAt": "2026-08-02T10:24:56.232Z",
    "updates": [
      {
        "id": "upd-1",
        "at": "2026-08-02T10:24:56.232Z",
        "source": "Redação",
        "text": "Início da cobertura ao vivo. Equipe monitora fontes oficiais e correspondentes."
      },
      {
        "id": "upd-2",
        "at": "2026-08-02T03:24:56.232Z",
        "source": "Agência",
        "text": "Primeira confirmação independente chega à mesa. Texto em verificação cruzada."
      },
      {
        "id": "upd-3",
        "at": "2026-08-01T20:24:56.232Z",
        "source": "Correspondente",
        "text": "Cena local descrita com cautela — sem especulação além do observado."
      },
      {
        "id": "upd-4",
        "at": "2026-08-01T13:24:56.232Z",
        "source": "Redação",
        "text": "Linha do tempo reorganizada. Âncoras de atualização permanecem estáveis."
      },
      {
        "id": "upd-5",
        "at": "2026-08-04T06:24:56.232Z",
        "source": "Especialista",
        "text": "Contexto rápido para leitores que acabaram de entrar na cobertura."
      },
      {
        "id": "upd-6",
        "at": "2026-08-03T23:24:56.232Z",
        "source": "Redação",
        "text": "Última atualização desta demonstração. Em produção, o CMS alimenta este feed."
      }
    ]
  },
  {
    "id": "live-2",
    "slug": "demo-regional",
    "title": "AO VIVO — Frente regional (br-rio)",
    "summary": "Segundo demo de live-blog para validar rotas e UI.",
    "updatedAt": "2026-08-01T20:24:56.232Z",
    "updates": [
      {
        "id": "upd-r1",
        "at": "2026-08-01T20:24:56.232Z",
        "source": "Redação regional",
        "text": "Abertura do blog regional com foco em impacto local."
      },
      {
        "id": "upd-r2",
        "at": "2026-08-01T13:24:56.232Z",
        "source": "Prefeitura / órgão local (demo)",
        "text": "Nota oficial demonstrativa — rotular fonte é obrigatório neste layout."
      }
    ]
  }
];
